name: CI

on:
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.5.2
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Linting Starlark"
        run: bazel run @buildifier_prebuilt//:buildifier -- -mode check -lint warn -r .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.5.2
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Build"
        run: |
          bazel build //pmd/wrapper:bin
          bazel build //pmd/wrapper:bin --enable_bzlmod=false
      - name: "Analysis tests"
        run: |
          bazel test //tests/analysis:tests
          bazel test //tests/analysis:tests --enable_bzlmod=false
      - name: "Integration tests"
        run: |
          bash tests/integration/suite.sh
          bash tests/integration/suite.sh --enable_bzlmod=false         
