name: CI

on:
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4.1.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Linting Starlark"
        run: bazel run @buildifier_prebuilt//:buildifier -- -mode check -lint warn -r .

  build-bzlmod:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4.1.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Configure Bazel"
        run: cp .github/workflows/ci.bazelrc .
      - name: "Build"
        run: bazel build //... --enable_bzlmod=True
      - name: "Unit tests"
        run: bazel test //... --enable_bzlmod=True
      - name: "Integration tests"
        run: bash tests/integration/suite.sh
  build-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v4.1.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Configure Bazel"
        run: cp .github/workflows/ci.bazelrc .
      - name: "Build"
        run: bazel build //... --enable_bzlmod=False
