name: CI

on:
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Linting Starlark"
        run: bazel run @buildifier_prebuilt//:buildifier -- -mode check -lint warn -r .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: "Install JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Configure Bazel"
        run: cp .github/workflows/.bazelrc .
      - name: "Fetch"
        run: bazel fetch //pmd/wrapper:bin
      - name: "Build"
        run: bazel build //pmd/wrapper:bin
      - name: "Analysis tests"
        run: bazel test //tests/analysis:tests
      - name: "Integration tests"
        run: bash tests/integration/suite.sh
