name: CI

on:
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.6.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Linting Starlark"
        run: bazel run @buildifier_prebuilt//:buildifier -- -mode check -lint warn -r .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3.6.0
      - name: "Install JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: "Setup Bazelisk"
        uses: bazelbuild/setup-bazelisk@v2
      - name: "Configure Bazel"
        run: cp .github/workflows/.bazelrc .
      - name: "Build"
        run: bazel build //...
      - name: "Analysis tests"
        run: bazel test //...
      - name: "Integration tests"
        run: bash tests/integration/suite.sh
